In [88]:
import pandas as pd
import numpy as np
df = pd.read_csv('D:/Leads.csv')

In [89]:
Y = df['Converted']
num_col = ['TotalVisits','Page Views Per Visit','Total Time Spent on Website']
cat_col = ['Lead Origin','Lead Source','Last Activity','Last Notable Activity','Specialization','City','What is your current occupation','What matters most to you in choosing a course']
df1 = df[num_col]
df2 = df[cat_col]
X = pd.concat([df1,df2],axis=1)

In [90]:
from sklearn.impute import SimpleImputer
from sklearn.metrics import accuracy_score,roc_auc_score
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer = imputer.fit(X[num_col])
  
X[num_col] = imputer.transform(X[num_col])

In [91]:
imputer = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
imputer = imputer.fit(X[cat_col])
  
X[cat_col] = imputer.transform(X[cat_col])

In [92]:
from sklearn.model_selection import train_test_split,GridSearchCV
from sklearn.preprocessing import StandardScaler
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.3)

In [93]:
scaler = StandardScaler()
X_train[num_col] = scaler.fit_transform(X_train[num_col])
X_test[num_col] = scaler.fit_transform(X_test[num_col])

C:\Users\HP\anaconda3\lib\site-packages\pandas\core\frame.py:3678: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[col] = igetitem(value, i)
C:\Users\HP\anaconda3\lib\site-packages\pandas\core\frame.py:3678: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[col] = igetitem(value, i)

In [94]:
X_train_cat = X_train[cat_col]
X_test_cat = X_test[cat_col]
X_train_cat['train'] = 1
X_train_cat['test'] = 0
X_test_cat['train'] = 0
X_test_cat['test'] = 1

C:\Users\HP\AppData\Local\Temp/ipykernel_25424/583419466.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_train_cat['train'] = 1
C:\Users\HP\AppData\Local\Temp/ipykernel_25424/583419466.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_train_cat['test'] = 0
C:\Users\HP\AppData\Local\Temp/ipykernel_25424/583419466.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_test_cat['train'] = 0
C:\Users\HP\AppData\Local\Temp/ipykernel_25424/583419466.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_test_cat['test'] = 1

In [95]:
X_cat_comb = pd.concat([X_train_cat,X_test_cat])
X_cat_comb = pd.get_dummies(X_cat_comb,columns=cat_col,drop_first=True)
X_cat_comb

,train,test,Lead Origin_Landing Page Submission,Lead Origin_Lead Add Form,Lead Origin_Lead Import,Lead Origin_Quick Add Form,Lead Source_Direct Traffic,Lead Source_Facebook,Lead Source_Google,Lead Source_Live Chat,...,City_Select,City_Thane & Outskirts,City_Tier II Cities,What is your current occupation_Housewife,What is your current occupation_Other,What is your current occupation_Student,What is your current occupation_Unemployed,What is your current occupation_Working Professional,What matters most to you in choosing a course_Flexibility & Convenience,What matters most to you in choosing a course_Other
7675,1,0,1,0,0,0,1,0,0,0,...,0,0,0,0,0,0,1,0,0,0
2079,1,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
4125,1,0,1,0,0,0,1,0,0,0,...,0,1,0,0,0,0,1,0,0,0
8296,1,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,1,0,0,0
486,1,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19,0,1,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,1,0,0,0
945,0,1,0,0,0,0,0,0,1,0,...,1,0,0,0,0,0,1,0,0,0
728,0,1,1,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,1,0,0
8615,0,1,1,0,0,0,1,0,0,0,...,0,0,0,0,0,0,1,0,0,0
6334,0,1,1,0,0,0,1,0,0,0,...,0,0,0,0,0,0,1,0,0,0

In [96]:
X_train_cate = X_cat_comb[X_cat_comb['train'] ==1]
X_test_cate = X_cat_comb[X_cat_comb['test'] ==1]

In [97]:
X_train_cate.drop('train',axis=1,inplace=True)
X_train_cate.drop('test',axis=1,inplace=True)

C:\Users\HP\anaconda3\lib\site-packages\pandas\core\frame.py:4906: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

In [98]:
X_test_cate.drop('train',axis=1,inplace=True)
X_test_cate.drop('test',axis=1,inplace=True)

In [99]:
X_train_fin = pd.concat([X_train[num_col],X_train_cate],axis=1)
X_train_fin

,TotalVisits,Page Views Per Visit,Total Time Spent on Website,Lead Origin_Landing Page Submission,Lead Origin_Lead Add Form,Lead Origin_Lead Import,Lead Origin_Quick Add Form,Lead Source_Direct Traffic,Lead Source_Facebook,Lead Source_Google,...,City_Select,City_Thane & Outskirts,City_Tier II Cities,What is your current occupation_Housewife,What is your current occupation_Other,What is your current occupation_Student,What is your current occupation_Unemployed,What is your current occupation_Working Professional,What matters most to you in choosing a course_Flexibility & Convenience,What matters most to you in choosing a course_Other
7675,-0.287049,-0.169969,1.554064,1,0,0,0,1,0,0,...,0,0,0,0,0,0,1,0,0,0
2079,0.126242,0.728207,-0.256839,1,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
4125,1.572759,0.580008,1.862575,1,0,0,0,1,0,0,...,0,1,0,0,0,0,1,0,0,0
8296,-0.700340,-1.068146,-0.884813,0,0,0,0,0,0,0,...,1,0,0,0,0,0,1,0,0,0
486,-0.080404,-0.394514,0.351055,0,0,0,0,0,0,0,...,1,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6797,-0.287049,-0.169969,1.740266,1,0,0,0,1,0,0,...,0,0,0,0,0,0,1,0,0,0
3821,0.126242,-0.169969,-0.842826,0,0,0,0,0,0,0,...,1,0,0,0,0,0,1,0,0,0
3663,-0.700340,-1.068146,-0.884813,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
317,1.366114,1.177295,0.130169,0,0,0,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
3939,-0.080404,0.279119,-0.877511,1,0,0,0,1,0,0,...,0,0,0,0,0,0,1,0,0,0

In [100]:
X_test_fin = pd.concat([X_test[num_col],X_test_cate],axis=1)
X_test_fin

,TotalVisits,Page Views Per Visit,Total Time Spent on Website,Lead Origin_Landing Page Submission,Lead Origin_Lead Add Form,Lead Origin_Lead Import,Lead Origin_Quick Add Form,Lead Source_Direct Traffic,Lead Source_Facebook,Lead Source_Google,...,City_Select,City_Thane & Outskirts,City_Tier II Cities,What is your current occupation_Housewife,What is your current occupation_Other,What is your current occupation_Student,What is your current occupation_Unemployed,What is your current occupation_Working Professional,What matters most to you in choosing a course_Flexibility & Convenience,What matters most to you in choosing a course_Other
2550,-0.120880,0.347050,0.201120,1,0,0,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
4973,-0.120880,-0.425646,0.832056,0,0,0,0,0,0,0,...,1,0,0,0,0,0,1,0,0,0
2895,0.088890,0.862180,0.013298,1,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
8811,0.298660,1.377311,-0.125289,1,0,0,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
7285,-0.330649,-0.168081,-0.851048,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19,-0.120880,0.347050,-0.723402,0,0,0,0,0,0,0,...,1,0,0,0,0,0,1,0,0,0
945,-0.120880,0.347050,-0.145348,0,0,0,0,0,0,1,...,1,0,0,0,0,0,1,0,0,0
728,-0.540419,-0.683211,-0.852872,1,0,0,0,1,0,0,...,0,0,0,0,0,0,0,1,0,0
8615,-0.330649,-0.168081,-0.415228,1,0,0,0,1,0,0,...,0,0,0,0,0,0,1,0,0,0
6334,-0.120880,0.347050,-0.355052,1,0,0,0,1,0,0,...,0,0,0,0,0,0,1,0,0,0

In [105]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=50,max_depth=8)
li = list(range(1,100))
param = {'n_estimators':li}
grid = GridSearchCV(estimator=rf,param_grid=param,cv=5)
grid.fit(X_train_fin,Y_train)

GridSearchCV(cv=5,
             estimator=RandomForestClassifier(max_depth=8, n_estimators=50),
             param_grid={'n_estimators': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,
                                          13, 14, 15, 16, 17, 18, 19, 20, 21,
                                          22, 23, 24, 25, 26, 27, 28, 29, 30, ...]})

In [106]:
grid.best_params_

{'n_estimators': 46}

In [115]:
rf = RandomForestClassifier(n_estimators=46,min_samples_split=5)
rf.fit(X_train_fin,Y_train)

RandomForestClassifier(min_samples_split=5, n_estimators=46)

In [116]:
pred = rf.predict(X_test_fin)
accuracy = accuracy_score(Y_test,pred)
auc_score = roc_auc_score(Y_test,pred)

print(accuracy)
print(auc_score)

0.825036075036075
0.8073633750065938